print("it was raining in the city")
print("today's weather was bad")
print("i lost my pen in school today")
print("they selected me to be the team captain")
print("my classmate told me that i was good at maths")
print("i will handle goa homeworks by my self")
print("i took a survey and got a 100%")
print("parantheses are important for coding")
print("my friends are always incorrect when it comes to physics")
print("my grandmas personality is similar as my momas personality")
